Skip processing modules with parse errors
phylum-dev/vuln-reach pull request #38
Opened 2023-06-01 12:34 UTC by andreaphylum

This PR changes the `Tree` to `Module` conversion to be fallible, and makes it fail every time the tree contains errors. 

The algorithm already skips modules that aren't loadable by the module resolver; this means that a module with errors will be just skipped.

This is acceptable because a tree with errors won't be executable by a runtime, and thus anything in it will be unreachable.

Closes #27.

2023-06-01 19:09 UTC, cd-work requested changes
I'm mostly cautious of this change because I'm not certain that the errors here are "safe" to skip.

How do we know these are issues in the modules, rather than issues with our parser? And how do we make sure we take notice of these errors so we get the chance to fix them if necessary.

Also JavaScript is notoriously lazy, so it's possible that a partially parsed module still enables a vulnerability to be called, right?

2023-06-01 19:49 UTC, andreaphylum commented
> I'm mostly cautious of this change because I'm not certain that the errors here are "safe" to skip.

I agree, I want to look more into what could go wrong here. Though I feel like this particular case, like many similar to it, might end up requiring a lossy compromise of sorts.

> How do we know these are issues in the modules, rather than issues with our parser? 

We don't -- unfortunately `tree-sitter-javascript` is our source of truth in that matter. If it is compliant to the spec it should correctly parse all valid JavaScript code. This may or may not be the case, I haven't investigated, but we don't have a lot of recourse either way.

>And how do we make sure we take notice of these errors so we get the chance to fix them if necessary.

What we could do there is actually point`tree-sitter-javascript` to a large number of modules, take a sample of the ones that have errors in them, and then ensure that the code is actually containing errors. Fwiw, this has been the case so far for all the trees I analyzed that were failing to parse.

> Also JavaScript is notoriously lazy, so it's possible that a partially parsed module still enables a vulnerability to be called, right?

I don't have a definitive answer to that, but I think we could try to craft a script with errors in it and see whether any code gets executed.

My educated guess is that that's not going to happen because those parse errors happen at the AST level, and the tree that gets parsed by the interpreter is not really executable in any way. A bit of evidence towards that is that JavaScript has a feature called "hoisting" where declarations, even if they appear further down a scope, are always available from the top of the scope. So, for example:

```javascript
function foo() {
  console.log(a)  // a exists already, prints undefined
  console.log(b)  // throws ReferenceError
  var a = 3
}
```
but if there was an error in between the logs and the declaration, the interpreter could not know that `a` is an existing reference; this means that the tree has to be evaluated before `console.log(a)` is ever run.

On the other hand, different runtimes could offer different properties: I'd expect a browser's runtime to be more lenient towards errors than `node` or `deno`.

I think we can hold off on this a bit while we figure out the specifics.

2023-06-06 14:25 UTC, cd-work commented
I'd just like to add that I've also found a lot of TypeScript modules that were named `.js` in my testing. I don't quite understand why this is happening but we do currently fail hard on those.

2023-06-06 14:28 UTC, andreaphylum commented
> I'd just like to add that I've also found a lot of TypeScript modules that were named `.js` in my testing. I don't quite understand why this is happening but we do currently fail hard on those.

Might be worth investigating.

2023-06-06 14:29 UTC, cd-work approved these changes

2023-06-06 14:31 UTC, merged